import type { SaasContact360Input } from './saas-adapter';

export function createSaasContact360Fixture(): SaasContact360Input {
  return {
    contact: {
      id: 'contact-lucia',
      workspace_id: 'workspace-demo',
      phone: '+34600123421',
      name: 'Lucía Martín',
      email: 'lucia@clinica.example',
      source: 'ycloud',
      stage: 'qualified',
      tags: ['clínica', 'prioridad'],
      opt_in: true,
      updated_at: '2026-07-14T15:00:00.000Z',
    },
    conversation: {
      id: 'conversation-001',
      workspace_id: 'workspace-demo',
      contact_id: 'contact-lucia',
      state: 'ai_active',
      ai_enabled: true,
      unread_count: 1,
      last_message_at: '2026-07-14T15:10:00.000Z',
      window_expires_at: '2026-07-15T15:10:00.000Z',
    },
    lastMessage: {
      id: 'message-001',
      workspace_id: 'workspace-demo',
      conversation_id: 'conversation-001',
      direction: 'in',
      body: 'Quiero automatizar WhatsApp y las llamadas de la clínica.',
      status: 'read',
      created_at: '2026-07-14T15:10:00.000Z',
    },
    lastVoiceCall: {
      id: 'voice-call-001',
      workspace_id: 'workspace-demo',
      contact_id: 'contact-lucia',
      status: 'ended',
      started_at: '2026-07-14T14:00:00.000Z',
      duration_seconds: 183,
      summary: 'Busca atención multicanal para su clínica.',
      lead_status: 'qualified',
      ended_reason: 'customer-ended-call',
      created_at: '2026-07-14T14:00:00.000Z',
    },
    memory: {
      workspace_id: 'workspace-demo',
      contact_id: 'contact-lucia',
      summary: 'Gestiona una clínica y busca automatizar la atención.',
      interests: ['automatización', 'agendamiento'],
      preferences: { canal_propuesta: 'email' },
      objections: ['tiempo de implantación'],
      lead_status: 'qualified',
      next_step: 'Enviar propuesta y agendar demostración.',
      updated_at: '2026-07-14T15:11:00.000Z',
    },
    memoryItemCount: 4,
    latestDeal: {
      id: 'deal-001',
      workspace_id: 'workspace-demo',
      contact_id: 'contact-lucia',
      title: 'Automatización clínica',
      stage: 'contacted',
      value: 2400,
      currency: 'EUR',
      expected_close_date: '2026-07-31',
      updated_at: '2026-07-14T15:12:00.000Z',
    },
    pendingTasks: 1,
  };
}
