import type { MemoryMutationEvent } from './types';

export function createMemoryFixtures(): MemoryMutationEvent[] {
  return [
    {
      id: 'memory-event-1',
      kind: 'profile.upserted',
      workspaceId: 'workspace-demo',
      contactId: 'contact-lucia',
      source: 'whatsapp',
      occurredAt: '2026-07-14T09:00:00.000Z',
      displayName: 'Lucía Martín',
      phoneMasked: '+34 *** *** 421',
    },
    {
      id: 'memory-event-2',
      kind: 'summary.updated',
      workspaceId: 'workspace-demo',
      contactId: 'contact-lucia',
      source: 'automation',
      occurredAt: '2026-07-14T09:01:00.000Z',
      summary: 'Gestiona una clínica y busca automatizar la atención y las citas.',
      summarySources: ['whatsapp', 'voice'],
    },
    {
      id: 'memory-event-3',
      kind: 'item.upserted',
      workspaceId: 'workspace-demo',
      contactId: 'contact-lucia',
      source: 'whatsapp',
      occurredAt: '2026-07-14T09:02:00.000Z',
      item: {
        id: 'memory-lucia-need',
        category: 'need',
        value: 'Necesita reducir el tiempo de respuesta por WhatsApp.',
        source: 'whatsapp',
        confidence: 0.94,
        sensitivity: 'normal',
        createdAt: '2026-07-14T09:02:00.000Z',
        evidenceEntityId: 'conversation-001',
      },
    },
    {
      id: 'memory-event-4',
      kind: 'item.upserted',
      workspaceId: 'workspace-demo',
      contactId: 'contact-lucia',
      source: 'voice',
      occurredAt: '2026-07-14T09:05:00.000Z',
      item: {
        id: 'memory-lucia-preference',
        category: 'preference',
        value: 'Prefiere recibir propuestas por correo antes de una llamada.',
        source: 'voice',
        confidence: 0.88,
        sensitivity: 'normal',
        createdAt: '2026-07-14T09:05:00.000Z',
        evidenceEntityId: 'voice-call-001',
      },
    },
    {
      id: 'memory-event-5',
      kind: 'profile.upserted',
      workspaceId: 'workspace-demo',
      contactId: 'contact-daniel',
      source: 'manual',
      occurredAt: '2026-07-14T10:00:00.000Z',
      displayName: 'Daniel Ruiz',
      phoneMasked: '+34 *** *** 718',
    },
    {
      id: 'memory-event-6',
      kind: 'item.upserted',
      workspaceId: 'workspace-demo',
      contactId: 'contact-daniel',
      source: 'manual',
      occurredAt: '2026-07-14T10:01:00.000Z',
      item: {
        id: 'memory-daniel-instruction',
        category: 'instruction',
        value: 'No contactar durante el horario de apertura de su restaurante.',
        source: 'manual',
        confidence: 1,
        sensitivity: 'sensitive',
        createdAt: '2026-07-14T10:01:00.000Z',
      },
    },
  ];
}

